@isTest public class ParkLocatorTest {
@isTest static void testCallout() {             

        // This causes a fake response to be generated

       // Test.setMock(WebServiceMock.class, new ParkServiceMock());

        // Call the method that invokes a callout

        //Double x = 1.0;

        //Double result = AwesomeCalculator.add(x, y);

         

        //String country = 'Germany';

        //String[] result = ParkLocator.Country(country);

        //System.assertEquals(new List<String>{'Hamburg Wadden Sea National Park', 'Hainich National Park', 'Bavarian Forest National Park'}, result);

    }
}